build:
	gcc mutex.c -o mutex -lpthread -Wall
	gcc barrier.c -o barrier -lpthread -Wall
	gcc multiply_seq.c -o multiply_seq -lpthread -Wall
	gcc multiply.c -o multiply -lpthread -Wall
	gcc multiply2.c -o multiply2 -lpthread -Wall
	gcc multiply3.c -o multiply3 -lpthread -Wall
	gcc strassen.c -o strassen -lpthread -Wall
	gcc strassen2.c -o strassen2 -lpthread -Wall
clean:
	rm -rf mutex barrier multiply_seq multiply strassen multiply2 multiply3 strassen2
